import { create } from 'zustand'; // Import 'create' from zustand

// Define your Zustand store
const useRecipeStore = create(set => ({
  // 'recipes' is your state array, initialized as empty
  recipes: [],
  
  // 'addRecipe' is an action to add a new recipe to the 'recipes' array
  addRecipe: (newRecipe) => set(state => ({ 
    recipes: [...state.recipes, newRecipe] // Add newRecipe to the existing recipes
  })),
  
  // 'setRecipes' is an action to completely replace the 'recipes' array (e.g., for initial load)
  setRecipes: (recipes) => set({ recipes }) 
}));

export default useRecipeStore; // Export the hook generated by Zustand

